services:
  the-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-watcher
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config.yaml:/app/config.yaml
    network_mode: bridge
