/* For agents stuff */

ALTER TABLE Pings ADD COLUMN ram_usage INTEGER;
ALTER TABLE Pings ADD COLUMN ram_max INTEGER;
ALTER TABLE Pings ADD COLUMN cpu_cores INTEGER;
ALTER TABLE Pings ADD COLUMN cpu_usage FLOAT;
ALTER TABLE Pings ADD COLUMN disk_capacity INTEGER;
ALTER TABLE Pings ADD COLUMN disk_usage INTEGER;
ALTER TABLE Pings ADD COLUMN load_avg FLOAT;

CREATE TABLE Agents (
    id INTEGER PRIMARY KEY,
    token STRING NOT NULL,
    last_ping TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES Monitors(id)
);
