CREATE TABLE Logs (
    id INTEGER NOT NULL,
    status STRING NOT NULL,
    message STRING NOT NULL,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES Monitors(id) ON DELETE CASCADE
);
